version: '3.8'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: Dockerfile # Path to your Node.js Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - TOKEN_SECRET_KEY=does-not-matter
      - JWT_ACCESS_EXPIRES_IN=9028374920
      - JWT_REFRESH_EXPIRES_IN=9028374920873
      - JWT_REFRESH_SECRET=lorem-ipsum
      - JWT_ACCESS_SECRET=lorem-ipsum
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DBNAME=sdb
      - NODE_ENV=development
      - JWT_EMAIL_SECRET=akjkdsnajdnajnda
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017 # Expose MongoDB port
    volumes:
      - ./database/data/db:/data/db # Volume to persist MongoDB data
